- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install docker
    yum: name=docker state=present
  - name: start docker
    service: name=docker state=started
  - name: Install pip
    apt:
      name: python-pip
      update_cache: yes
      state: present
  - name: pull a docker image
    docker_image:
          name: devopsedu/webapp
          tag: latest
          source: pull
  - name: run the dockerfile
    command: docker run -itd -P devopsedu/webapp:latest
